---
# tasks file for NTP

# ============================================== Ping ==============================================

- name: Ping my servers
  become: true
  ansible.builtin.ping:

# ========================================= Блок для RedHat ========================================
# ==================================================================================================

- name: Block for RedHat
  when: ansible_os_family == "RedHat"
  become: true
  block:

    # ============================================= Chrony =============================================

    - name: Копирование файла chrony.conf
      become: true
      ansible.builtin.template:
        src: ntp/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: "0644"
        # force: true

    - name: Restart NTP Alma
      become: true
      ansible.builtin.service:
        state: restarted
        daemon_reload: true
        name: chronyd

# ========================================= Блок для Ubuntu ========================================
# ==================================================================================================

- name: Block for Ubuntu
  when: ansible_os_family == "Debian"
  become: true
  block:

    # ============================================== NTP ===============================================

    - name: Install NTP Ubuntu
      become: true
      ansible.builtin.apt:
        name: ntp

    - name: Копирование файла ntp.conf
      become: true
      ansible.builtin.template:
        src: ntp/ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: "0644"
        # force: true

    - name: Restart NTP Ubuntu
      become: true
      ansible.builtin.service:
        state: restarted
        name: ntp

# ==================================================================================================

- name: Set timezone to Europe/Moscow
  become: true
  community.general.timezone:
    name: Europe/Moscow