---
# handlers file for chrony

- name: Restart ssh Ubuntu
  become: true
  ansible.builtin.service:
    state: restarted
    name: ssh
    enabled: true

- name: Restart ssh RedHat
  become: true
  ansible.builtin.service:
    state: restarted
    name: sshd
    enabled: true
