---
- name: Create file1
  ansible.builtin.copy:
    dest: /home/fill/test/newfolder1/file1.txt
    mode: '0644'
    content: |
      Text Line1, in file1
      Text Line2, in file1
      Text Line3, {{ mytext }}

- name: Create file2
  ansible.builtin.copy:
    dest: /home/fill/test/newfolder2/file2.txt
    mode: '0644'
    content: |
      Text Line1, in file2
      Text Line2, in file2
      Text Line3, {{ mytext }}
