---
- name: Copy file
  hosts: all

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
    - name: Copy my home page to servers
      ansible.builtin.copy:
        src: "{{ source_file }}"              # Источник на Ansible-Master
        dest: "{{ destin_file }}"             # Папка назначения на host-машине
        mode: '0664'
        #remote_src: true                     # Показывает, что и источник тоже находится на host-машине
