---
# General playbook

- name: General playbook
  hosts: "all"

  roles:
    - role: ping
    - role: ssh-keys
    - role: passwordauthentication-no
    - role: sudoers
    - role: dns
      when: "'dns' not in inventory_hostname"
    - role: chrony
      when: "'ntp' not in inventory_hostname"
    - role: timezone
    - role: install
    # - role: reboot
