---
# General playbook

- name: General playbook
  hosts: "all"

  roles:
    - role: ping
    - role: ssh-keys
    - role: passwordauthentication-no
    - role: sudoers
    - role: dns
    - role: chrony
    - role: timezone
    - role: repository-local
    - role: install
    - role: reboot
