---
- name: Helm template install
  hosts: k8s_master1

# ansible-playbook Helm_Template_Install.yml --extra-var "helm_name=my-nginx helm_namespace=default file=/home/fill/K8SManifests/HelmChart_values_nginx.yaml"
# ansible-playbook Helm_Template_Install.yml --extra-var "helm_name=my-gifservice helm_namespace=default file=/home/fill/K8SManifests/HelmChart_values_gifservice.yaml"

  tasks:
    - name: Helm install
      kubernetes.core.helm:
        update_repo_cache: true
        name: "{{ helm_name }}"
        chart_ref: fillswimrepo/my-template-helmchart
        release_namespace: "{{ helm_namespace }}"
        values_files:
          - "{{ file }}"
