---

- name: Kolla-Ansible Prepare
  hosts: "all"

  roles:
    - role: chrony
    - role: timezone
    - role: sudoers
    - role: ssh-keys
    - role: install-docker
    - role: kolla-ansible-prepare
