---
- name: Install Apache and Upload my Web Page
  hosts: all

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
    - name: Install Apache WebServer
      ansible.builtin.apt:
        name: apache2

    - name: Create folder
      ansible.builtin.file:
        path: ./MyWebSite/
        state: directory
        mode: '0775'

    - name: Download index.html
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/fillswim/ansible/master/index.html
        dest: ./MyWebSite/index.html
        mode: '0664'

    - name: Copy my home page to servers
      ansible.builtin.copy:
        src: "{{ source_file }}"
        dest: "{{ destin_file }}"
        mode: '0664'
        remote_src: true
      notify: Restart Apache Handler

  handlers:
    - name: Restart Apache Handler
      ansible.builtin.service:
        name: apache2
        state: restarted
