---
- name: Copy indexes
  hosts: ansible_linux2

  vars:
    source_folder: /home/fill/MyWebSite2/
    destin_folder: /var/www/html

  tasks:

    - name: Create folder
      ansible.builtin.file:
        path: "{{ source_folder }}"
        state: directory
        mode: '0775'

    - name: Download indexes
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/fillswim/ansible/master/{{ item }}
        dest: "{{ source_folder }}/{{ item }}"
        mode: '0664'
      loop:
        - "index.j2"

    - name: Generate Index.thml
      ansible.builtin.template:
        src: "{{ source_folder }}/index.j2"
        dest: "{{ destin_folder }}/index.thml"
        mode: '0555'
      notify: Restart Apache Handler

  handlers:
    - name: Restart Apache Handler
      ansible.builtin.service:
        name: apache2
        state: restarted
