---
- name: Playbook for show setup var
  hosts: ansible_servers

  # Вывод всех переменных с хоста
  # ansible ansible_linux1 -m setup
  tasks:
    - name: Show setup var
      ansible.builtin.debug:
        var: ansible_default_ipv4.address
