---

- name: Adding-Other-Control-Nodes
  serial: 1                           # Выполнять роль будет одновременно только на одной ноде от и до
  order: sorted                       # Ноды будут выбираться в алфавитном порядке
  hosts: all

  roles:
    - role: 04-Adding-Other-Nodes
