---
- name: My Update Ubuntu playbook
  hosts: k8s_servers

  tasks:
    - name: Ping my servers
      ansible.builtin.ping:

    - name: Update
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
      become: true

    - name: Upgrade
      ansible.builtin.apt:
        upgrade: dist
      become: true
