---

- name: Block for RedHat
  when: ansible_os_family == "RedHat" or ansible_os_family == "RED"
  become: true
  block:

    - name: Скачивание opensearch-3.x.repo в /etc/yum.repos.d/
      ansible.builtin.get_url:
        url: "{{ opensearch_repo_url }}"
        dest: "{{ opensearch_repo_file }}"
        force: true
        owner: root
        group: root
        mode: '0644'

    - name: Установка пакета opensearch с переменной окружения
      ansible.builtin.yum:
        name: opensearch
        state: latest
      environment:
        OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"


- name: Block for Altlinux
  when: ansible_os_family == "Altlinux"
  become: true
  block:

    - name: Install OpenSearch in Altlinux
      ansible.builtin.package:
        name: opensearch
        state: present

- name: Скопировать "jvm.options"
  become: true
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "/etc/opensearch/jvm.options"
    owner: opensearch
    group: opensearch
    mode: "0640"

- name: Скопировать "opensearch.yml" для RedHat
  become: true
  when: ansible_os_family == "RedHat" or ansible_os_family == "RED"
  ansible.builtin.template:
    src: opensearch-redhat.yml.j2
    dest: "/etc/opensearch/opensearch.yml"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify:
    - Start OpenSearch

- name: Скопировать "opensearch.yml" для Altlinux
  become: true
  when: ansible_os_family == "Altlinux"
  ansible.builtin.template:
    src: opensearch-altlinux.yml.j2
    dest: "/etc/opensearch/opensearch.yml"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify:
    - Start OpenSearch
