---

- name: Скачивание opensearch-3.x.repo в /etc/yum.repos.d/
  ansible.builtin.get_url:
    url: "{{ opensearch_repo_url }}"
    dest: "{{ opensearch_repo_file }}"
    force: true
    owner: root
    group: root
    mode: '0644'

- name: Установка пакета opensearch с переменной окружения
  ansible.builtin.yum:
    name: opensearch
    state: present
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"

- name: Скопировать "jvm.options"
  become: true
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "/etc/opensearch/jvm.options"
    owner: opensearch
    group: opensearch
    mode: "0640"

- name: Скопировать "opensearch.yml"
  become: true
  ansible.builtin.template:
    src: opensearch.yml.j2
    dest: "/etc/opensearch/opensearch.yml"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify:
    - Start OpenSearch
