---

# ==============================================================================
#                                Установка OpenSearch
# ==============================================================================

- name: Block for RedHat
  when: ansible_os_family == "RedHat" or ansible_os_family == "RED"
  become: true
  block:

    - name: Скачивание opensearch-3.x.repo в /etc/yum.repos.d/
      ansible.builtin.get_url:
        url: "{{ opensearch_repo_url }}"
        dest: "{{ opensearch_repo_file }}"
        force: true
        owner: root
        group: root
        mode: '0644'

    - name: Установка пакета opensearch с переменной окружения
      ansible.builtin.yum:
        name: opensearch
        state: latest
      environment:
        OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ opensearch_admin_password }}"


- name: Block for Altlinux
  when: ansible_os_family == "Altlinux"
  become: true
  block:

    - name: Install OpenSearch in Altlinux
      ansible.builtin.package:
        name: opensearch
        state: present

- name: Скопировать "jvm.options"
  become: true
  ansible.builtin.template:
    src: jvm.options.j2
    dest: "/etc/opensearch/jvm.options"
    owner: opensearch
    group: opensearch
    mode: "0640"

# ==============================================================================
#                                Создание папок
# ==============================================================================

# Создание папки "data" для OpenSearch
- name: Проверка существования папки "{{ opensearch_data_folder }}"
  ansible.builtin.stat:
    path: "{{ opensearch_data_folder }}"
  register: data_folder_output

- name: Создание папки "{{ opensearch_data_folder }}"
  when:
    - data_folder_output.stat.exists is false
  ansible.builtin.file:
    path: "{{ opensearch_data_folder }}"
    state: directory
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    mode: "0750"

# Создание папки "logs" для OpenSearch
- name: Проверка существования папки "{{ opensearch_logs_folder }}"
  ansible.builtin.stat:
    path: "{{ opensearch_logs_folder }}"
  register: logs_folder_output

- name: Создание папки "{{ opensearch_logs_folder }}"
  when:
    - logs_folder_output.stat.exists is false
  ansible.builtin.file:
    path: "{{ opensearch_logs_folder }}"
    state: directory
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    mode: "0750"

# ==============================================================================
#                     Копирование конфигурационных файлов
# ==============================================================================

- name: Скопировать "opensearch.yml" для RedHat
  become: true
  when: ansible_os_family == "RedHat" or ansible_os_family == "RED"
  ansible.builtin.template:
    src: opensearch-redhat.yml.j2
    dest: "/etc/opensearch/opensearch.yml"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify:
    - Start OpenSearch

- name: Скопировать "opensearch.yml" для Altlinux
  become: true
  when: ansible_os_family == "Altlinux"
  ansible.builtin.template:
    src: opensearch-altlinux.yml.j2
    dest: "/etc/opensearch/opensearch.yml"
    owner: opensearch
    group: opensearch
    mode: "0640"
  notify:
    - Start OpenSearch
