---
# tasks file for 01-prepare-vm-for-k8s-check
- name: Check SWAP
  ansible.builtin.shell: swapon
  register: swapon_results
  failed_when: swapon_results.stdout != ""

- name: Check SELinux
  ansible.builtin.shell: getenforce
  register: getenforce_results
  failed_when: getenforce_results.stdout != "Disabled"

- name: Check Firewall
  ansible.builtin.shell: systemctl status firewalld
  register: firewalld_results
  failed_when: "'Active: inactive (dead)' not in firewalld_results.stdout"

- name: Check Chrony
  ansible.builtin.shell: systemctl status chronyd
  register: chronyd_results
  failed_when: "'Active: active (running)' not in chronyd_results.stdout"

- name: Check Containerd
  ansible.builtin.shell: systemctl status containerd
  register: containerd_results
  failed_when: "'Active: active (running)' not in containerd_results.stdout"

- name: Check crictl
  ansible.builtin.shell: crictl images
  register: crictl_results
  failed_when: "'IMAGE               TAG                 IMAGE ID            SIZE' not in crictl_results.stdout"

- name: Check kubectl
  ansible.builtin.shell: kubectl version
  register: kubectl_results
  failed_when: "'Client Version: v' not in kubectl_results.stdout"
