---
# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

# =========================== Checking that the node is already attached ===========================

- name: Checking that the node is already attached
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Join control node {{ inventory_hostname }}
  when: not kubeadm_ca.stat.exists
  ansible.builtin.shell:
    cmd: |
      kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path }} \
      --token {{ hostvars[groups['k8s_masters'][0]].join_token }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].ca_cert_hash }} \
      --node-name {{ inventory_hostname }}
