---
# tasks PasswordAuthentication No

- name: Block for RedHat
  when: ansible_os_family == "RedHat" or ansible_os_family == "RED"
  become: true
  block:

    - name: Replace line first time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: false
      notify:
        - Restart ssh RedHat

    - name: Replace line second time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: false
      notify:
        - Restart ssh RedHat

- name: Block for Ubuntu
  when: ansible_os_family == "Debian"
  become: true
  block:

    - name: Replace line first time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: false
      notify:
        - Restart ssh Ubuntu

    - name: Replace line second time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: false
      notify:
        - Restart ssh Ubuntu
