---
# tasks PasswordAuthentication No

- name: Replace line first time
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    state: present
    backup: false
  notify:
    - Restart ssh Ubuntu

- name: Replace line second time
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    state: present
    backup: false
  notify:
    - Restart ssh Ubuntu
