---
- name: Install Apache and Upload my Web Page
  hosts: ansible_servers

  vars:
    source_folder: ./MyWebSite2
    destin_folder: /var/www/html

  tasks:
    - name: Show ansible_os_family
      ansible.builtin.debug:
        var: ansible_os_family

    - name: Block for Debian
      when: ansible_os_family == "Debian"
      become: true
      block:
        - name: Install Apache WebServer on Debian
          ansible.builtin.apt:
            name: apache2

        - name: Copy files to servers on Debian
          ansible.builtin.copy:
            src: "{{ source_folder }}/{{ item }}"
            dest: "{{ destin_folder }}"
            mode: '0664'
          loop:
            - "au.png"
            - "de.png"
            - "fr.png"
            - "gb.png"
            - "index.html"

        - name: Restart Apache for Debian
          ansible.builtin.systemd_service:
            name: apache2
            state: restarted

    - name: Block for RedHat
      when: ansible_os_family == "RedHat"
      become: true
      block:
        - name: Install Apache WebServer on RedHat
          ansible.builtin.yum:
            name:
              - httpd

        - name: Copy files to servers
          ansible.builtin.copy:
            src: "{{ source_folder }}/{{ item }}"
            dest: "{{ destin_folder }}"
            mode: '0664'
          loop:
            - "au.png"
            - "de.png"
            - "fr.png"
            - "gb.png"
            - "index.html"

        - name: Restart Apache Handler for RedHat
          ansible.builtin.systemd_service:
            name: httpd
            state: restarted
