---
- name: Install Apache RedHat
  hosts: ansible_linux5

  tasks:
    - name: Install Apache WebServer on RedHat
      become: true
      ansible.builtin.yum:
        name:
          - httpd

    - name: Start Apache and Enable it on every boot
      become: true
      ansible.builtin.systemd_service:
        name: httpd
        state: started
        enabled: true
