---
- name: Missing sudo password playbook
  hosts: "{{ selected_hosts }}"

  # Set host
  # ansible-playbook Missing_sudo_password.yaml --extra-var "selected_hosts=ansible_linux1 username=****" -b -K

  tasks:
    - name: Ping my servers
      ansible.builtin.ping:

    - name: Create file
      ansible.builtin.copy:
        dest: /etc/sudoers.d/{{ username }}
        mode: '0644'
        content: |
          {{ username }} ALL=(ALL) NOPASSWD: ALL
