---
- name: Disable PasswordAuthentication playbook
  hosts: "{{ selected_hosts }}"

  # Set host
  # ansible-playbook PasswordAuthentication_No.yaml --extra-var "selected_hosts=jenkins_node1" -b -K

  tasks:
    - name: Ping my servers
      ansible.builtin.ping:

    - name: Replace line first time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: no

    - name: Replace line second time
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        state: present
        backup: no

    - name: Restart SSH Service
      become: true
      ansible.builtin.systemd_service:
        name: ssh
        state: restarted