---
- name: Test connection to my servers
  hosts: K8s-Alt
  # connection: local # ansible-playbook Ping.yml -b -K

  tasks:
    - name: Ping my servers
      become: true
      ansible.builtin.ping:
