---
- name: Start Apache Web servers
  hosts: all

  tasks:
    - name: Start Apache
      become: true
      ansible.builtin.systemd_service:
        name: apache2
        enabled: true
        state: started
