---
# tasks file for Install-Docker

# ============================================== Ping ==============================================

- name: Ping my servers
  become: true
  ansible.builtin.ping:

# ========================================= Блок для Ubuntu ========================================
# ==================================================================================================

- name: Block for Ubuntu
  when: ansible_os_family == "Debian"
  become: true
  block:

    # ======================================= Upgrade system =======================================

    - name: Обновление системы Ubuntu
      throttle: 1
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
      become: true

    # ===================================== Установка пакетов ======================================

    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg

    # ================================== Добавление репозитория ====================================

    - name: Create /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Delete Docker GPG key file
      become: true
      ansible.builtin.file:
        path: "{{ docker_gpg_path }}"
        state: absent

    - name: Download Docker GPG key file
      become: true
      ansible.builtin.get_url:
        url: "{{ docker_gpg_link }}"
        dest: "{{ docker_gpg_path }}"
        mode: '0644'
        force: true

    - name: Add Docker GPG apt Key
      become: true
      ansible.builtin.apt_key:
        url: "{{ docker_gpg_link }}"
        state: present

    - name: Add Docker Repository
      become: true
      ansible.builtin.apt_repository:
        repo: "{{ docker_deb_url }}"
        state: present
        update_cache: true

    # ======================================= Upgrade system =======================================

    - name: Обновление системы Ubuntu
      throttle: 1
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
      become: true

    # ===================================== Установка Docker =======================================

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    # ========================================= Проверка ===========================================

    - name: Verify that you can run Docker
      become: true
      community.docker.docker_container:
        detach: false
        name: hello-world
        image: library/hello-world
      register: results
      failed_when: "'This message shows that your installation appears to be working correctly.' not in results.container.Output"

    - name: Show hello-world output
      ansible.builtin.debug:
        msg: "{{ results.container.Output }}"
