---
# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

# ========================================== Get join_path =========================================

- name: Get join_path
  ansible.builtin.shell: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' | cut -c9-
  register: join_path

- name: Create variable join_path
  ansible.builtin.set_fact:
    join_path: "{{ join_path.stdout }}"

- name: Show join_path
  ansible.builtin.debug:
    var: join_path

# ========================================= Get join_token =========================================

- name: Get join_token
  ansible.builtin.shell: kubeadm token create
  register: join_token

- name: Create variable join_token
  ansible.builtin.set_fact:
    join_token: "{{ join_token.stdout }}"

- name: Show join_token
  ansible.builtin.debug:
    var: join_token

# ======================================== Get ca_cert_hash ========================================

- name: Get ca_cert_hash
  ansible.builtin.shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
    openssl rsa -pubin -outform der 2>/dev/null | \
    openssl dgst -sha256 -hex | sed 's/^.* //'
  register: ca_cert_hash

- name: Create variable ca_cert_hash
  ansible.builtin.set_fact:
    ca_cert_hash: "{{ ca_cert_hash.stdout }}"

- name: Show ca_cert_hash
  ansible.builtin.debug:
    var: ca_cert_hash

# ====================================== Get certificate_key =======================================

- name: Get certificate_key
  ansible.builtin.shell: kubeadm init phase upload-certs --upload-certs | tail -1
  register: certificate_key

- name: Create variable certificate_key
  ansible.builtin.set_fact:
    certificate_key: "{{ certificate_key.stdout }}"

- name: Show certificate_key
  ansible.builtin.debug:
    var: certificate_key
