---
# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

# =========================== Checking that the node is already attached ===========================

- name: Checking that the node is already attached
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Join control node {{ inventory_hostname }}
  when: not kubeadm_ca.stat.exists
  ansible.builtin.hell:
    cmd: |
      kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path }} \
      --token {{ hostvars[groups['k8s_masters'][0]].join_token }} \
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].ca_cert_hash }} \
      --certificate-key {{ hostvars[groups['k8s_masters'][0]].certificate_key }} \
      --node-name {{ inventory_hostname }} \
      --control-plane

- name: Создание папки /root/.kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Copy /etc/kubernetes/admin.conf to /root/.kube/config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0600"
