---
# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

# ==================================== Rollout Restart CoreDNS =====================================

- name: Rollout Restart CoreDNS
  ansible.builtin.shell: kubectl -n kube-system rollout restart deployment coredns
